Repository ITurres/tesla-booking-front-end, pull requests merged in 2024-01, with the labels that each got.

#11 Issue #1 🎫: Project setup (CRA redux architecture, images, GitHub actions, Linters, Documentation and License, etc)
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  LICENSE
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  public/tesla-apple-touch-icon.png
  public/tesla-black-word-logo.png
  public/tesla-red-logo-favicon.png
  public/tesla-red-logo.png
  public/tesla-red-word-logo.png
  src/app/App.jsx
  src/app/store.js
  src/components/Layout.jsx
  src/features/feature1/feature1.jsx
  src/features/feature1/feature1API.js
  src/features/feature1/feature1Slice.js
  src/helpers/apiRequest.js
  src/index.js
  src/json/reservations.json
  src/json/vehicles.json
  src/pages/xPage.jsx
  src/styles/_variables.scss
  src/styles/base/normalize.css
  src/styles/index.scss
  src/tests/setupTests.js
Labels: documentation, enhancement, setup

#12 Issue #3 🎫: vehiclesList and vehicleItem | components
  public/vehicles.json
  src/app/App.jsx
  src/app/store.js
  src/components/Layout.jsx
  src/features/vehiclesList/SplideCarousel.jsx
  src/features/vehiclesList/VehicleItem.jsx
  src/features/vehiclesList/VehiclesList.jsx
  src/features/vehiclesList/vehicleListSlice.js
  src/features/vehiclesList/vehicleListThunk.js
  src/helpers/apiRequest.js
  src/helpers/getRandomId.js
  src/pages/VehiclesPage.jsx
  src/styles/_variables.scss
  src/styles/features/vehiclesList/SplideCarousel.scss
  src/styles/features/vehiclesList/VehiclesList.scss
  src/styles/pages/VehiclesPage.scss
Labels: enhancement, UI/UX

#13 Feature/side panel
  public/tesla-red-logo.png
  public/tesla-red-word-logo.png
  public/users.json
  public/vehicles.json
  src/app/App.jsx
  src/app/store.js
  src/components/Layout.jsx
  src/components/NavigationLinks.jsx
  src/components/SidePanel.jsx
  src/features/feature1/feature1.jsx
  src/features/feature1/feature1API.js
  src/features/feature1/feature1Slice.js
  src/features/users/usersSlice.js
  src/features/vehiclesList/SplideCarousel.jsx
  src/helpers/apiRequest.js
  src/index.js
  src/styles/components/NavigationLinks.scss
  src/styles/components/SidePanel.scss
  src/styles/features/vehiclesList/SplideCarousel.scss
  src/styles/index.scss
  src/styles/pages/VehiclesPage.scss
Labels: enhancement, UI/UX

#14 Hot fix for SidePanel
  src/app/assets/images/tesla-red-word-logo.png
  src/components/SidePanel.jsx
  src/features/vehiclesList/SplideCarousel.jsx
  src/styles/components/NavigationLinks.scss
  src/styles/components/SidePanel.scss
  src/styles/features/vehiclesList/SplideCarousel.scss
  src/styles/index.scss
  src/styles/pages/VehiclesPage.scss
Labels: enhancement, bug fix, UI/UX

#15 Issue #5 🎫: Reservation Page and related components
  public/reservations.json
  src/app/App.jsx
  src/app/store.js
  src/components/NavigationLinks.jsx
  src/features/reservations/ReservationForm.jsx
  src/features/reservations/reservationsSlice.js
  src/features/reservations/reservationsThunk.js
  src/features/users/userThunk.js
  src/features/users/usersSlice.js
  src/features/vehiclesList/SplideCarousel.jsx
  src/pages/ReservationPage.jsx
  src/styles/components/SidePanel.scss
  src/styles/features/reservations/ReservationForm.scss
  src/styles/features/vehiclesList/SplideCarousel.scss
  src/styles/index.scss
  src/styles/pages/ReservationPage.scss
  src/styles/pages/VehiclesPage.scss
Labels: enhancement, UI/UX

#17 Feature/vehicle detail
  public/vehicle.json
  public/vehicles.json
  src/app/App.jsx
  src/app/store.js
  src/features/reservations/ReservationForm.jsx
  src/features/reservations/reservationsSlice.js
  src/features/vehicles/SplideCarousel.jsx
  src/features/vehicles/VehicleDetail.jsx
  src/features/vehicles/VehicleItem.jsx
  src/features/vehicles/vehiclesSlice.js
  src/features/vehicles/vehiclesThunk.js
  src/helpers/apiRequest.js
  src/styles/components/NavigationLinks.scss
  src/styles/components/SidePanel.scss
  src/styles/features/vehicles/SplideCarousel.scss
  src/styles/features/vehicles/VehicleDetail.scss
  src/styles/index.scss
  src/styles/pages/VehiclesPage.scss
Labels: enhancement, UI/UX
